"""
SkillMatrix AI - Reports Routes

Features:
- View report history
- Generate reports
- Generate career-specific reports
- Download generated PDF reports
"""

import os

from flask import (
    render_template,
    redirect,
    url_for,
    flash,
    send_file,
    current_app,
)

from flask_login import login_required, current_user

from app.blueprints.reports import reports_bp
from app.utils.decorators import student_required
from app.models import Report, CareerRole
from app.services import report_service


# =========================================================
# REPORT HISTORY
# =========================================================

@reports_bp.route("/")
@login_required
@student_required
def index():
    """
    Display all reports generated by the logged-in student.
    """

    reports = (
        Report.query
        .filter_by(
            student_id=current_user.id
        )
        .order_by(
            Report.generated_at.desc()
        )
        .all()
    )

    careers = (
        CareerRole.query
        .filter_by(
            is_active=True
        )
        .order_by(
            CareerRole.title
        )
        .all()
    )

    return render_template(
        "reports/index.html",
        reports=reports,
        careers=careers,
    )


# =========================================================
# REPORT GENERATORS
# =========================================================

_REPORT_GENERATORS = {

    "Employability":
        lambda student:
        report_service.generate_employability_report(
            student
        ),

    "Skill":
        lambda student:
        report_service.generate_skill_report(
            student
        ),

    "Resume":
        lambda student:
        report_service.generate_resume_report(
            student
        ),

    "Interview":
        lambda student:
        report_service.generate_interview_report(
            student
        ),

    "Placement":
        lambda student:
        report_service.generate_placement_report(
            student
        ),

    "LearningProgress":
        lambda student:
        report_service.generate_learning_progress_report(
            student
        ),

    "Communication":
        lambda student:
        report_service.generate_communication_report(
            student
        ),

    "CGPA":
        lambda student:
        report_service.generate_cgpa_report(
            student
        ),
}


# =========================================================
# GENERATE NORMAL REPORT
# =========================================================

@reports_bp.route(
    "/generate/<report_type>",
    methods=["POST"]
)
@login_required
@student_required
def generate(report_type):
    """
    Generate a normal student report.
    """

    generator = _REPORT_GENERATORS.get(
        report_type
    )

    # -----------------------------------------------------
    # Validate report type
    # -----------------------------------------------------

    if not generator:

        flash(
            "Unknown report type.",
            "danger"
        )

        return redirect(
            url_for("reports.index")
        )

    # -----------------------------------------------------
    # Generate report
    # -----------------------------------------------------

    try:

        report = generator(
            current_user
        )

        if not report:

            flash(
                f"{report_type} report could not be generated.",
                "danger"
            )

        else:

            flash(
                f"{report_type} report generated successfully!",
                "success"
            )

    except Exception as e:

        current_app.logger.exception(
            "Report generation failed"
        )

        flash(
            f"Could not generate {report_type} report: {str(e)}",
            "danger"
        )

    return redirect(
        url_for("reports.index")
    )


# =========================================================
# GENERATE CAREER REPORT
# =========================================================

@reports_bp.route(
    "/generate/career/<int:career_role_id>",
    methods=["POST"]
)
@login_required
@student_required
def generate_career(career_role_id):
    """
    Generate a report for a specific career role.
    """

    role = CareerRole.query.get_or_404(
        career_role_id
    )

    try:

        report = (
            report_service.generate_career_report(
                current_user,
                role
            )
        )

        if not report:

            flash(
                "Career report could not be generated.",
                "danger"
            )

        else:

            flash(
                f"Career report for {role.title} "
                f"generated successfully!",
                "success"
            )

    except Exception as e:

        current_app.logger.exception(
            "Career report generation failed"
        )

        flash(
            f"Could not generate career report: {str(e)}",
            "danger"
        )

    return redirect(
        url_for("reports.index")
    )


# =========================================================
# DOWNLOAD REPORT
# =========================================================

@reports_bp.route(
    "/download/<int:report_id>"
)
@login_required
@student_required
def download(report_id):
    """
    Download a PDF report belonging to the
    currently logged-in student.
    """

    # -----------------------------------------------------
    # Get report belonging ONLY to current student
    # -----------------------------------------------------

    report = (
        Report.query
        .filter_by(
            id=report_id,
            student_id=current_user.id
        )
        .first_or_404()
    )

    # -----------------------------------------------------
    # Validate database file path
    # -----------------------------------------------------

    if not report.file_path:

        flash(
            "This report does not have a PDF file.",
            "danger"
        )

        return redirect(
            url_for("reports.index")
        )

    # -----------------------------------------------------
    # Get UPLOAD_FOLDER
    # -----------------------------------------------------

    upload_folder = current_app.config.get(
        "UPLOAD_FOLDER",
        "uploads"
    )

    # Make upload folder absolute

    upload_folder = os.path.abspath(
        upload_folder
    )

    # -----------------------------------------------------
    # Normalize stored path
    # -----------------------------------------------------

    stored_path = str(
        report.file_path
    ).replace(
        "\\",
        "/"
    ).strip()

    # -----------------------------------------------------
    # Remove leading slash if present
    # -----------------------------------------------------

    stored_path = stored_path.lstrip("/")

    # -----------------------------------------------------
    # Handle:
    #
    # uploads/reports/file.pdf
    #
    # and:
    #
    # reports/file.pdf
    #
    # -----------------------------------------------------

    if stored_path.startswith(
        "uploads/"
    ):

        stored_path = stored_path[
            len("uploads/"):
        ]

    # -----------------------------------------------------
    # Build absolute path
    # -----------------------------------------------------

    absolute_path = os.path.abspath(
        os.path.join(
            upload_folder,
            stored_path
        )
    )

    # -----------------------------------------------------
    # Security check
    #
    # Prevent ../ path traversal
    # -----------------------------------------------------

    try:

        common_path = os.path.commonpath(
            [
                upload_folder,
                absolute_path
            ]
        )

    except ValueError:

        common_path = ""

    if common_path != upload_folder:

        current_app.logger.error(
            "Invalid report file path: %s",
            absolute_path
        )

        flash(
            "Invalid report file path.",
            "danger"
        )

        return redirect(
            url_for("reports.index")
        )

    # -----------------------------------------------------
    # Check PDF exists
    # -----------------------------------------------------

    if not os.path.isfile(
        absolute_path
    ):

        current_app.logger.error(
            "Report file not found: %s",
            absolute_path
        )

        flash(
            "Report PDF was not found. "
            "Please generate the report again.",
            "danger"
        )

        return redirect(
            url_for("reports.index")
        )

    # -----------------------------------------------------
    # Download PDF
    # -----------------------------------------------------

    return send_file(
        absolute_path,
        mimetype="application/pdf",
        as_attachment=True,
        download_name=os.path.basename(
            absolute_path
        )
    )